### ISSUE TITLE
ZMK Combos with no layers show up on all layers

### ISSUE THREAD

**Issue by infused-kim** [caksoylar/keymap-drawer#10]
Hi, another small issue that I just came across.

I wanted to disable a macro in my zmk config, but keep it in case I change my mind later. So I set the layers setting to empty. This disabled the macro in the firmwar.

But when I updated my keymap image, the macros with the empty layer setting showed up on all layers.

Example config:
```yaml

# Shows up on all layers
    combo_grave {
      timeout-ms = <COMBO_TERM_SLOW>;
      global-quick-tap-ms = <COMBO_GLOBAL_QUICKTAP>;

      key-positions = <RM3 RM4>;
      layers = <>;
      bindings = <&kp GRAVE>;
    };

# Shows up only on one layer
    combo_md_code_block {
      timeout-ms = <COMBO_TERM_SLOW>;
      global-quick-tap-ms = <COMBO_GLOBAL_QUICKTAP>;

      key-positions = <RM2 RM3 RM4>;
      layers = <BASE>;
      bindings = <&m_type_md_code_block>;
    };
```

**Comment by infused-kim** [comment]
As a workaround in the meantime change [this line](https://github.com/caksoylar/keymap-drawer/blob/a02814ea1508839d16f54f615e6f37a4555ef628/keymap_drawer/keymap.py#L89) to:
```python
            for layer_name in combo.layers if combo.layers else []:
```

**Comment by caksoylar** [comment]
Interesting! The ZMK default behavior when `layers` property isn't specified is to enable it on all layers so I was honoring that for with the current code. However I didn't consider the edge case where you specify an *empty* `layers` property, but I am not sure I'd call it a ZMK edge case or keymap drawer one 😄 

Because of above, your suggestion is probably not a good idea. Just out of curiosity, wouldn't commenting out the combo node be a better solution for disabling a combo? This way it won't get compiled in and won't incur any runtime cost.

**Comment by infused-kim** [comment]
Yeah it is a much better idea... I only thought of it after I already posted this issue. I think we can ignore this request and close this issue.

Thank you!
