### ISSUE TITLE
Preprocess keys in `raw_bindings_map` before using it

### ISSUE THREAD

**Issue by infused-kim** [caksoylar/keymap-drawer#11]
I have a behavior like this which expects two parameter, but doesn't actually use the second parameter:
```
        lt_num_word: lt_num_word {
            compatible = "zmk,behavior-hold-tap";
            label = "lt_num_word";
            #binding-cells = <2>;
            flavor = "balanced";
            tapping-term-ms = <200>;
            bindings = <&mo>, <&num_word>;
        };
```

And in my keymap I use it like `&lt_num_word NUM 0`. Unfortunately it shows up like this in the graphic:
<img width="873" alt="Screenshot 2023-03-07 at 13 52 12" src="https://user-images.githubusercontent.com/7404004/223537341-bc98008c-3853-4b17-b5f0-5c0677cd24f9.png">

Perhaps the solution could be as simple as allowing the config to overwrite the entire behavior:
```yaml
  raw_binding_map:
    '&lt_num_word NUM 0': {t: "Num\nWord", h: 'Num'}
```

**Comment by caksoylar** [comment]
Thanks for reporting, I thought the `raw_binding_map` would work but I think it gets snagged on the `NUM` definition which would get replaced by the layer index during preprocessing. So you could try replacing it in the key but it is pretty ugly. Unfortunately this would be non-trivial to solve within the current framework where preprocessing precedes all other processing. Maybe we need a step before preprocessing to extract these `#define`s and add more involved logic to use them during parsing.

(I think `keymap-editor` attempts something similar but it is a more difficult scenario since it has to go back to devicetree after you edit the keymap.)

**Comment by caksoylar** [comment]
Another option to improve the parsing behavior would be to use the behavior type rather than the parameter when the parameter is `0` (and behavior type isn't layer changing), assuming it is a dummy parameter.

**Comment by infused-kim** [comment]
> I think it gets snagged on the `NUM` definition which would get replaced by the layer index during preprocessing

That's exactly what happened. After replacing `NUM` with the layer number it is working well, thank you.

This is working well enough for me, but perhaps an even better solution would be to run the `raw_binding_map` through the preprocessor?

**Comment by caksoylar** [comment]
> This is working well enough for me, but perhaps an even better solution would be to run the raw_binding_map through the preprocessor?

This is really smart! 😄 I'll see if this is feasible, it would need to be merged with the keymap to get the defines and then split back.
