### ISSUE TITLE
Piping to base keymap file results in error

### ISSUE THREAD

**Issue by lilactown** [caksoylar/keymap-drawer#15]
The following causes the parse command to fail:

```
$ keymap parse -b keymap.yaml -z board.keymap > keymap.yaml
Traceback (most recent call last):
  File "/Users/lilactown/Library/Caches/pypoetry/virtualenvs/keymap-drawer-BqElniGm-py3.10/bin/keymap", line 6, in <module>
    sys.exit(main())
  File "/Users/lilactown/Code/keymap-drawer/keymap_drawer/__main__.py", line 157, in main
    parse(args, config.parse_config)
  File "/Users/lilactown/Code/keymap-drawer/keymap_drawer/__main__.py", line 53, in parse
    base = KeymapData(layers=yaml_data["layers"], combos=yaml_data.get("combos", []), layout=None, config=None)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by caksoylar** [comment]
I think this is a usual shell issue (and I am not sure I can explain it very well, but I'll attempt): When you redirect the output to a file with `program >x` the shell opens that file for writing immediately and this prevents the program from reading from it, leading to that error. That's why some command line tools have switches like `perl -i file` to do in-place modifications on the file.

I would recommend doing something like below which would be safer in case the program errors out as well:
```shell
keymap parse -b keymap.yaml -z board.keymap > new.yaml && mv new.yaml keymap.yaml
```

**Comment by lilactown** [comment]
Makes sense! That's pretty similar to what I ended up with.
