### ISSUE TITLE
Populate transparent keys

### ISSUE THREAD

**Issue by chrissicool** [caksoylar/keymap-drawer#18]
My ZMK config features a lot of `&trans` keys. Unfortunately, keymap-drawer only shows them as blank keys. Please consider to update transparent keys from the same key position on the layer below, transitively going down to the base layer.

Thank you.

**Comment by caksoylar** [comment]
Hi there,

Key presses are only captured by layers that are active, so we can't really know in advance what a transparent key position will resolve to. For example if there is a `&trans` on layer 2, `&kp A` on the same position on layer 1, and `&kp B` on the base layer, pressing that key will output `A` only if layer 2 is active and will output `B` otherwise. So I am not sure how we would want to visualize that.

However I think it might be a good idea to distinguish `&none` and `&trans` in general, so I wouldn't be opposed to using a special symbol for parsing (probably configurable). For example QMK Configurator uses the `▽` symbol:
![image](https://user-images.githubusercontent.com/7876996/233228362-aef2ac9d-a6ee-4fe2-afcf-62cd725946bb.png)
Would that be helpful?

**Comment by chrissicool** [comment]
Hi,

that would help, indeed. I am not convinced that we need a special symbol for `&none` is really necessary. At least as long as there is a symbol for `&kp SPACE` (i.e. `␣`). But that would likely make Unicode characters mandatory.

I played around and got the following configuration block to work nicely for me:

```
draw_config:
  svg_style: |
    /* color accent for trans keys */
    rect.trans, rect.combo.trans {
      fill: #ddddee;
    }
parse_config:
  raw_binding_map:
    '&trans': {h: '', t: '▽', s: '', type: trans}
```

Something similar likely works for `&none` as well. Thanks for pointing me into the right direction.

Does it make sense to provide some default color styles for transparent keys? I don't know.

**Comment by caksoylar** [comment]
I really like the idea of assigning special classes to transparent/null keys, I think they warrant special treatment in case user wants to customize them. Regarding their default styling, I would want experiment a bit and see if I like how it looks.

I probably wouldn't put any legend on the none keys but we can add a config to add the triangle unicode symbol (which should be supported by default by SVG renderers) automatically for tansparent keys.
