### ISSUE TITLE
kinesis zmk keymap: "default_layer" (82) does not match physical layout specification (76)

### ISSUE THREAD

**Issue by rtomaszewski** [caksoylar/keymap-drawer#21]
im using the default kinesis firmware. The custom keymap that i created can be seen here: 
https://github.com/rtomaszewski/Adv360-Pro-ZMK

When i try to parse it using the web page im getting this error:
https://caksoylar-keymap-drawer-streamlitapp-2a0rau.streamlit.app/?example_yaml=showcase.yaml

validationError: 1 validation error for KeymapData __root__ Number of keys on layer "default_layer" (82) does not match physical layout specification (76) (type=assertion_error)
Traceback:
File "/app/keymap-drawer/streamlit/app.py", line 327, in main
    svg = draw(st.session_state.keymap_yaml, parse_config(st.session_state.kd_config).draw_config)
File "/app/keymap-drawer/streamlit/app.py", line 47, in draw
    drawer = KeymapDrawer(
File "/app/keymap-drawer/keymap_drawer/draw.py", line 31, in __init__
    self.keymap = KeymapData(config=config, **kwargs)
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__

**Comment by caksoylar** [comment]
Hi, thank you for reporting. I noticed that the transform KA360 uses gained extra key positions since the last time I checked and created the entry for automatic lookup: https://github.com/caksoylar/keymap-drawer/blob/main/resources/zmk_keyboard_layouts.yaml#L77

It now looks closest to the [80 key layout](https://config.qmk.fm/#/ergodox_ez/base/LAYOUT_ergodox_80) however it still has two extra bindings in the middle and I am not sure what they correspond to. 

I guess I will experiment with their editor and see how it visualizes the two bindings. I guess we could use [their own info.json spec](https://github.com/rtomaszewski/Adv360-Pro-ZMK/blob/V2.0/config/info.json) and incorporate it as a [custom physical layout](https://github.com/caksoylar/keymap-drawer/tree/main/resources/qmk_layouts).

**Comment by caksoylar** [comment]
Their situation seems a bit messy, where they added key positions for switches that don't exist, such as extra bindings for 2u thumb keys and some others. However they hide those in the GUI editor by making them zero height keys, so I basically copied that approach and added a custom layout json (`qmk_keyboard: adv360`). Please give it a shot and let me know.

**Comment by rtomaszewski** [comment]
i can see now new error assuming that your online app is using the fixed code. Ive noticed as well that on the left side the layout  name has changed: 
layout: {qmk_keyboard: adv360}

### Error

`ValidationError: 1 validation error for KeymapData __root__ Number of keys on layer "default_layer" (82) does not match physical layout specification (84) (type=assertion_error)
Traceback:
File "/app/keymap-drawer/streamlit/app.py", line 327, in main
    svg = draw(st.session_state.keymap_yaml, parse_config(st.session_state.kd_config).draw_config)
File "/app/keymap-drawer/streamlit/app.py", line 47, in draw
    drawer = KeymapDrawer(
File "/app/keymap-drawer/keymap_drawer/draw.py", line 31, in __init__
    self.keymap = KeymapData(config=config, **kwargs)
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__`

**Comment by caksoylar** [comment]
I think this is because I added the layout corresponding to the latest upstream config, but your fork is behind a bit: https://github.com/rtomaszewski/Adv360-Pro-ZMK/compare/V2.0...KinesisCorporation:Adv360-Pro-ZMK:V2.0

Specifically, it doesn't have this commit adding two extra key positions: https://github.com/rtomaszewski/Adv360-Pro-ZMK/commit/bdfd6475b480a6ae095ecc10181d68ef54a4736a
