### ISSUE TITLE
Provide config option to enable drawing of held key's binding

### ISSUE THREAD

**Issue by titus-ong** [caksoylar/keymap-drawer#23]
My keymap has two ways of going to another layer, either through holding a key with &mo or using a combo for &tog. The &mo key on that layer has its own binding to be used for the &tog option so I would like to display it on the layer. However, the keymap drawing only highlights the held key and does not show the binding (I looked through the config options provided but could not find a relevant config). Would it be possible to provide a config option to draw the bindings of held keys?

**Comment by caksoylar** [comment]
Hey there, you mean that the output of parsing (e.g. with `keymap parse`) does not have the tap/hold legends on the `&mo` key and simply produces `{t: held}` right? This was a [very recent change I made](https://github.com/caksoylar/keymap-drawer/commit/dc5945088fd1faa68881d75d89f8a89b9dc705ec) after adding legends for transparent keys, so that they don't have the trans legend `▽` for most keymaps.

However I did not consider you might want to keep the legend for keymaps where there are multiple ways to get to the same layer, since parsing only assigns held keys to the first way it finds anyway. User feedback like this issue helps me to understand use cases better, so thanks for that. I'll add a config option so you can keep the old behavior.

**Comment by caksoylar** [comment]
One question: If we preserve the legends of held keys, would you prefer that be unconditional or should it still erase the `▽` legend if it is a `&trans` position?

**Comment by caksoylar** [comment]
I opted to go with the "smart" approach where the binding will be deleted only if it is transparent in the first place. This way we don't have to introduce a new config entry.

If that works for you I will make a bug fix release. If not, let me know.

**Comment by titus-ong** [comment]
Thanks for the quick fix, I think the smart approach sounds good. Will let you know if there's any issue once I've tested the new release.

**Comment by caksoylar** [comment]
Thanks, released v0.7.1 and it is on pypi.
