### ISSUE TITLE
Feature request: holds for combos

### ISSUE THREAD

**Issue by sartak** [caksoylar/keymap-drawer#3]
Love the new keymap-drawer! I'm using it on https://github.com/sartak/keyboard#keymap :)

One feature that would be nice to support holds for combos. This is pretty easy in ZMK with a combo that triggers a hold-tap. It's also possible in QMK though you kinda have to roll your own timers and such.

This would let me simplify my keymap - rather than having separate "Alpha" and "Alpha (hold)" layers, I could have something like:

```yaml
combos:
- {"tap":"LC", "hold":"⌘LC", "p":[30,31]}
- {"tap":"AltBS", "hold":"Hyper", "p":[31,32]}
```

Alternatively, it might be good enough to support `type` styling options for combos like there are for keys:

```yaml
combos:
- {"k":"LC", "p":[30,31]}
- {"k":"⌘LC", "p":[30,31], "type":"ghost or green or whatever"}
```

Thanks for making this tool!

**Comment by caksoylar** [comment]
> Love the new keymap-drawer! I'm using it on https://github.com/sartak/keyboard#keymap :)

Thanks, and that's awesome! Although I could selfishly recommend you add a link to the tool near the representation 😆 

Hold-taps on combos do work right now, but you have to nest the tap/hold under the `k/key` field, like:
```yaml
- {k: {tap:"LC", hold:"⌘LC"}, "p":[30,31]}
```
You can also see it in the commented out combos on Miryoku example: https://github.com/caksoylar/keymap-drawer/blob/main/examples/miryoku.yaml#L57
(I think the newly added `shifted` field is ignored on combos however, if you have a use case for it I can enable it.)

> Alternatively, it might be good enough to support type styling options for combos like there are for keys:

Yeah, I think it wouldn't hurt to make the current combo styling the default, but let it respect the `type` field inside the `key` field if provided. I'll make that change; I'll also remove the restriction from the `type` field so you can define new CSS classes inside the [configuration](https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L67) and use it to refer to them.

**Comment by sartak** [comment]
Thanks for the quick response!

> Hold-taps on combos do work right now

Doh. `{tap: "LC", hold: "⌘LC"}` _does_ work :) I missed that in the schema. Feel free to close this issue! Here's what it looks like out of the box:

<img width="699" alt="スクリーンショット 2023-02-09 20 07 04" src="https://user-images.githubusercontent.com/45430/217975293-2ac20c51-373d-4892-8ad8-b74632d3219c.png">

The combo hold-taps look good! But now that I've folded in my separate "(hold)" layers, I'm noticing a new problem: vertical combos obscure the hold behavior of the key above them (e.g. in the rightmost column, `⌘A` is hidden under `:`)

I'm not sure there's any great solution to that. Especially for my symbol layer where every vertical pair has a combo. (So for example moving the hold to the top would just be moving problem without solving it). I could move all the combos off the keys entirely, and rely on dendrons, but that might be a little too difficult to parse visually for the 20 combos on the symbol layer. Actually, maybe not, since some combos can go on the inside between the halves, and the rest can go on the outside..

Only other thing I can think is special casing the specific situation of a combo below a key with a hold. That could push the key's tap and hold behaviors upwards, like so:

<img width="301" alt="スクリーンショット 2023-02-09 20 26 42" src="https://user-images.githubusercontent.com/45430/217977031-56e65f07-080c-40b6-98cc-3430fda0e70a.png">

That'd probably look even worse on a rowstag or ortho board than it does on this colstag though 😄 

If you have any other ideas, I'm game to try. If you want to noodle with it, I pushed the [hold keymap](https://raw.githubusercontent.com/sartak/keyboard/hold-keymap/keymap.json) and the [svg it generates](https://raw.githubusercontent.com/sartak/keyboard/hold-keymap/images/keymap.svg) to a branch.

> I think the newly added shifted field is ignored on combos however, if you have a use case for it I can enable it.

I do use shifted combos (distinct from holds) but only for steno-style word chords, not for the basic combos I'd put in my keymap. So, no need to add it on my account.

> I'll also remove the restriction from the `type` field so you can define new CSS classes

That sounds great!

> Although I could selfishly recommend you add a link to the tool near the representation 😆

Totally fair - added!

**Comment by caksoylar** [comment]
> The combo hold-taps look good! But now that I've folded in my separate "(hold)" layers, I'm noticing a new problem: vertical combos obscure the hold behavior of the key above them (e.g. in the rightmost column, ⌘A is hidden under :)

Yeah, I think some rendering issues are inevitable with the current iteration of the drawing code and requires manual intervention. What I would do (within the current limitations) is move all vertical combos of the sort to either `left` or `right` aligns, which doesn't look as neat but it is functional. [Here is a modified keymap I made](https://caksoylar.github.io/keymap-drawer?keymap_yaml=H4sIAAAAAAAC_83Xy04TURgH8L1PcQzqgBZhppSWeqXlbrlIy13EoRwo6bSnTqdigxiiiZpoDCCJLowLCWCiiW5cufMBfIg-iad0Zvh_3DwhIZENDD_-3zfn1hkssyxKTpQtP8xlZ7K8PCtMey7K5rltLxabikucF1bOWWaZ28XoOcbarULGrP7QyJYdsxBlYwGWEZZMVN58GFsBSAAkECYAJhCGAIYQYgAxhEmASYQugC6EQYBBhBGAEQRNfvn29jVSHDJxhGGAYYQkQBIhBZBC6AboRugH6EcYABhA6AToROgF6EVoB2hHuAtwF6EPoA9hFGAUoQOgA-EOwB2EcYBxhB6AHoSrZEED_nq2W_M2n0OsvPgJReQVwS-7Hv75ReDNVz_1cpfI2tZ-vedEXm57otVpVUmWc7PCwsOlPdDgbh6QUTxFeop0D-AeySz7GU3asoZ4AVIXSOoidrpIaIUUXCEFmyDVRFJ1JFWnKR437RLeyCVCl5EuE7qBdAOpHqAe4TrAdVLsJha7idQA0EAyjZhpRLoCcIVknmDmCdk3q5u4Q1c3Se425m4jzQDMkMwUWY4pjXbbId12EO8D3Sclp0nJae0MDuOfX2d5FgdKuVluk7OYTNuc51kyIxy6Y1txzlsJhZBChFqQWgjF7MWFjMNGCqRPf8nh5HFp80ckNiQf02zILBU5yQ3wx47qCUsuLTrpDEuY-QU6xiDebZCQgWQQ0pF0Qs1IzYRGhVXK8YPDr7xYI5thjeI7gu8orhNcp7hBcIPcSkKks6y28HQ-2vD22whFkCKEwkjho9a8Qywd6OTOxmGYFCLHevNNgyVH-98fdviRXztgXaV82lkUeXLEYkI4LCHMOXdAmnbEN_cVixc52dbwixNix7VwXzRT5CDGUiF6SQ93LMXiFjftk272hFuJpXRa3aCXwYPNUmJhwVJv5r7CHfP3aSFfNuQrfSPLRvcXdkzYc95C9ZQL3K6mJU0F9QALGtPyypJXe_8FBNwXloD7YTmNtRJxK4v_AMT9Qs2ykK5eaFgW8rOGzAbVs9p5zYvq4QAzwv-IMmZG2d45JFVu7VeJyCqR01WJ7ldpk1XaTlXlGtY4XYnfn_0acimMZq9ILe2mLD5PQ1t-SG4EQ1cLbfshuXCGoRSqPPvmp4IyFVRLvf7up1pkqkUtterPhWylq7X6_cPLyEHpioN69ckLyTnX1ea89qm7NySZUZvy6ku4G5LToCtOw8f3fqeQnLzQkalDG6nycdOPtcpYq2Ks9uSuxmQzXbVZ7ZFeTcleunKvdS8lz78eVk1teCl53vXICam_OfJ5SD4RAAA%3D), where I merged some of your combos by specifying multiple layers and added the align specs.

> Only other thing I can think is special casing the specific situation of a combo below a key with a hold. That could push the key's tap and hold behaviors upwards, like so:

You might notice that the [drawing code](https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/draw.py) is not particularly complex, since it currently draws all elements independently. A smarter drawing algorithm which considers interactions between different elements would be great but I think that endeavor might be left for a version 2.0 😄

**Comment by caksoylar** [comment]
> > I'll also remove the restriction from the type field so you can define new CSS classes

> That sounds great!

Turns out how we use CSS is currently a bit messy, I'll try to clean it up and add this functionality soon; I can give you a ping when that happens!

**Comment by caksoylar** [comment]
@sartak If you are interested, I pushed the changes that would let you pass a custom class in the `type` fields of keys and combos, for which you can define CSS classes in the [`draw_config.svg_style` variable](https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L54) and hopefully all the CSS classes make a little more sense now.

**Comment by sartak** [comment]
Thanks! ❤️
