### ISSUE TITLE
Alternative combo displays

### ISSUE THREAD

**Issue by jbarr21** [caksoylar/keymap-drawer#39]
I understand if this is too custom of an ask, but when there are a lot of combos like in Ardux, the display can become unreadable. Would it be possible to add the ability to draw 25-50% versions of the keymap w/ the selected keys highlighted similar to how displayed on [keymap editor's combo page](https://nickcoutsos.github.io/keymap-editor/) or [Artsey's layout diagram](https://raw.githubusercontent.com/artseyio/artsey/main/layout%20diagrams/current.jpg)?

**Comment by caksoylar** [comment]
I have thought about this before and you are right, this style makes more sense for certain layouts. I didn't like how much room it would take but scaling the layouts down might be good enough. 

Moving out the combo drawing code to a separate module from the main `draw` module is going to be a prerequisite but otherwise this shouldn't be too hard to implement, I think. Then we can have two combo drawer methods, one for each type.
