### ISSUE TITLE
Separate Combos on ZMK

### ISSUE THREAD

**Issue by t18n** [caksoylar/keymap-drawer#53]
Combos are valid across all layers so showing it multiple times is not necessary. Also, it covers the keys if someone uses combos extensively. I think having a separate draw for combo only would be a better approach
![image](https://github.com/caksoylar/keymap-drawer/assets/14198542/29826906-ef52-4941-8381-cf7e566defd0)

**Comment by caksoylar** [comment]
I don't intend to change the default behavior since I think the diagram should reflect the true behavior, i.e. that combos can be triggered on all layers by default. However there are a few options to draw combos separately:
1. Use [`--keys-only` or `--combos-only`](https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/__main__.py#L130) options in the command line to draw layers without combos, then layers with only combos. You can combine the latter with [`--select-layers`](https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/__main__.py#L129) to only draw combos for one of the layers.
2. Use [`separate_combo_diagrams` draw config option](https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L46), which draws all of them like below. This option ignores the layer filter completely. 
![0f957bdc-2da2-4369-be8c-2135058e63d4](https://github.com/caksoylar/keymap-drawer/assets/7876996/52771168-9cff-4596-a80e-163d4a533692)
3. Use [`zmk_combos` parse config](https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L383) to override the `layers` property for each combo

**Comment by t18n** [comment]
Thank you @caksoylar. Do you have an example on how to add these flags into the Github actions config? Here is my current config 
https://github.com/t18n/zmk-config-corne/blob/main/.github/workflows/draw-keymaps.yml

**Comment by caksoylar** [comment]
Doing 2. or 3. is simple: Just add a config file (see https://github.com/t18n/zmk-config-corne/blob/main/.github/workflows/draw-keymaps.yml#L18 on where to put it in the repo) and add the options I mentioned. E.g. for option 2 the minimum content you need is
```yaml
draw_config:
  separate_combo_diagrams: true
```

Approach 1. is more complicated since it involves calling `keymap draw` multiple times with different arguments. While you can pass command line arguments using this option https://github.com/t18n/zmk-config-corne/blob/main/.github/workflows/draw-keymaps.yml#L21 it will still call the command once. You'd need to modify the reusable workflow file at https://github.com/caksoylar/keymap-drawer/blob/main/.github/workflows/draw-zmk.yml or incorporate a modified version into your file above to do that.

**Comment by t18n** [comment]
@caksoylar I probably have done it wrong but when I added the configuration https://github.com/t18n/zmk-config-corne/blob/main/keymap_drawer.config.yaml, the generated SVG is empty

**Comment by caksoylar** [comment]
I'll close the issue, but please let me know if you have any issues implementing the suggestions above.
