### ISSUE TITLE
ZMK profile numbering inconsistency

### ISSUE THREAD

**Issue by quintuple-lained** [caksoylar/keymap-drawer#99]
profiles 0-4 all get incremented by 1 to be more human readable, profiles beyond this dont seem to get the same treatment, leading to two "BT 5" profiles in the graphic despite them actually being BT 4 and 5
image that shows this issue:
![image](https://github.com/caksoylar/keymap-drawer/assets/160709820/6c0b9838-541c-4207-8dc7-613634407d47)
my repository where this issue occurs
https://github.com/quintuple-lained/lained-ergonaut-keymap

**Comment by caksoylar** [comment]
Hi, the parser by default doesn't touch the profile numbers besides putting them in the `hold` field (bottom legend). The 0-4 to 1-5 mapping is because of these items in the config that override the legends: https://github.com/quintuple-lained/lained-ergonaut-keymap/blob/main/keymap-drawer/config.yaml#L23-L27 (I assume you copied this from my config 😄)

So if you remove those overrides, or add overrides for profiles 5-9, you can get consistent behavior.

**Comment by quintuple-lained** [comment]
im sorry for not knowing this, thank you for pointing this out

**Comment by caksoylar** [comment]
No worries!
